### ISSUE TITLE
MinkowskiEngine required for fine-tuning?

### ISSUE THREAD

**Issue by tomsynativ** [vishalned/MMEarth-train#2]
I followed INSTALL.MD and it mentioned that MinkowskiEngine only needs to be installed for pre-training. However, when running `./slurm_scripts/slurm_fine_tune_seg.sh`, I got the following error:

`Traceback (most recent call last):
  File "/opt/conda/envs/rsfms/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/rsfms/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/RSFMs/main_finetune.py", line 34, in <module>
    import models.convnextv2 as convnextv2
  File "/home/ubuntu/RSFMs/models/convnextv2.py", line 12, in <module>
    from .utils import LayerNorm, GRN
  File "/home/ubuntu/RSFMs/models/utils.py", line 14, in <module>
    from MinkowskiEngine import SparseTensor
ImportError: cannot import name 'SparseTensor' from 'MinkowskiEngine' (unknown location)`

So, I assume it needs to be installed for fine-tuning as well?

**Comment by vishalned** [comment]
Hey, so finetuning does not use sparse tensors, but i see that the error is because some of the functions in utils.py contains calls to the sparse tensors, but for finetuning we dont use them.

For a quick fix you can just comment the Minkowski import, or move the functions somewhere else. I will work on fixing it.
